// <auto-generated />
using System;
using LocalBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250118141034_Pez ")]
    partial class Pez
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalShared.Entities.Cultivo.ClsMPlantas", b =>
                {
                    b.Property<Guid>("PltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PltDtUtmModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PltNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PltStdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PltUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PltId");

                    b.HasIndex("PltNombre")
                        .IsUnique();

                    b.ToTable("Plantas");
                });

            modelBuilder.Entity("LocalShared.Entities.Cultivo.ClsMTipoCultivo", b =>
                {
                    b.Property<Guid>("TipCltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipCltDescripcion")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("TipCltDtUtmModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipCltNombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("TipCltStdCultivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TipCltUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TipCltId");

                    b.HasIndex("TipCltNombre")
                        .IsUnique();

                    b.ToTable("Cultivos");
                });
#pragma warning restore 612, 618
        }
    }
}
