// <auto-generated />
using System;
using LocalBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250213215325_nuevosistema")]
    partial class nuevosistema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalShared.Entities.Dispositivos.ClsMDispositivos", b =>
                {
                    b.Property<Guid>("IdDispisitivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAsignacionSistema")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMarca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipoDispositivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdDispisitivo");

                    b.HasIndex("SN")
                        .IsUnique()
                        .HasFilter("[SN] IS NOT NULL");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("LocalShared.Entities.Dispositivos.ClsMEstadosDispositivos", b =>
                {
                    b.Property<Guid>("IdEstadoDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipoDispositivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEstadoDispositivo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosDispositivos");
                });

            modelBuilder.Entity("LocalShared.Entities.Dispositivos.ClsMLogsEstados", b =>
                {
                    b.Property<Guid>("IdLogsEstados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDispositivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEstadoDsipositivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MyProperty")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLogsEstados");

                    b.HasIndex("IdLogsEstados")
                        .IsUnique();

                    b.ToTable("LogsEstados");
                });

            modelBuilder.Entity("LocalShared.Entities.Dispositivos.ClsMTipoDispositivo", b =>
                {
                    b.Property<Guid>("IdTipoDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoDispositivo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoDispositivos");
                });
#pragma warning restore 612, 618
        }
    }
}
